//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadFileInfo", Namespace="https://fias.nalog.ru/WebServices/Public/DownloadService.asmx/")]
    public partial class DownloadFileInfo : object
    {
        
        private long VersionIdField;
        
        private string TextVersionField;
        
        private string FiasCompleteDbfUrlField;
        
        private string FiasCompleteXmlUrlField;
        
        private string FiasDeltaDbfUrlField;
        
        private string FiasDeltaXmlUrlField;
        
        private string Kladr4ArjUrlField;
        
        private string Kladr47ZUrlField;
        
        private string GarXMLFullURLField;
        
        private string GarXMLDeltaURLField;
        
        private string DateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long VersionId
        {
            get
            {
                return this.VersionIdField;
            }
            set
            {
                this.VersionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TextVersion
        {
            get
            {
                return this.TextVersionField;
            }
            set
            {
                this.TextVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FiasCompleteDbfUrl
        {
            get
            {
                return this.FiasCompleteDbfUrlField;
            }
            set
            {
                this.FiasCompleteDbfUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FiasCompleteXmlUrl
        {
            get
            {
                return this.FiasCompleteXmlUrlField;
            }
            set
            {
                this.FiasCompleteXmlUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FiasDeltaDbfUrl
        {
            get
            {
                return this.FiasDeltaDbfUrlField;
            }
            set
            {
                this.FiasDeltaDbfUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FiasDeltaXmlUrl
        {
            get
            {
                return this.FiasDeltaXmlUrlField;
            }
            set
            {
                this.FiasDeltaXmlUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Kladr4ArjUrl
        {
            get
            {
                return this.Kladr4ArjUrlField;
            }
            set
            {
                this.Kladr4ArjUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Kladr47ZUrl
        {
            get
            {
                return this.Kladr47ZUrlField;
            }
            set
            {
                this.Kladr47ZUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string GarXMLFullURL
        {
            get
            {
                return this.GarXMLFullURLField;
            }
            set
            {
                this.GarXMLFullURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string GarXMLDeltaURL
        {
            get
            {
                return this.GarXMLDeltaURLField;
            }
            set
            {
                this.GarXMLDeltaURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", ConfigurationName="ServiceReference.IDownloadService")]
    public interface IDownloadService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetAllDownloadFileI" +
            "nfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.DownloadFileInfo[]> GetAllDownloadFileInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetLastDownloadFile" +
            "Info", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetLastDownloadFileInfoResponse> GetLastDownloadFileInfoAsync(ServiceReference.GetLastDownloadFileInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastDownloadFileInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastDownloadFileInfo", Namespace="https://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", Order=0)]
        public ServiceReference.GetLastDownloadFileInfoRequestBody Body;
        
        public GetLastDownloadFileInfoRequest()
        {
        }
        
        public GetLastDownloadFileInfoRequest(ServiceReference.GetLastDownloadFileInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLastDownloadFileInfoRequestBody
    {
        
        public GetLastDownloadFileInfoRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastDownloadFileInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastDownloadFileInfoResponse", Namespace="https://fias.nalog.ru/WebServices/Public/DownloadService.asmx/", Order=0)]
        public ServiceReference.GetLastDownloadFileInfoResponseBody Body;
        
        public GetLastDownloadFileInfoResponse()
        {
        }
        
        public GetLastDownloadFileInfoResponse(ServiceReference.GetLastDownloadFileInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://fias.nalog.ru/WebServices/Public/DownloadService.asmx/")]
    public partial class GetLastDownloadFileInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.DownloadFileInfo GetLastDownloadFileInfoResult;
        
        public GetLastDownloadFileInfoResponseBody()
        {
        }
        
        public GetLastDownloadFileInfoResponseBody(ServiceReference.DownloadFileInfo GetLastDownloadFileInfoResult)
        {
            this.GetLastDownloadFileInfoResult = GetLastDownloadFileInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IDownloadServiceChannel : ServiceReference.IDownloadService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DownloadServiceClient : System.ServiceModel.ClientBase<ServiceReference.IDownloadService>, ServiceReference.IDownloadService
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DownloadServiceClient() : 
            base(DownloadServiceClient.GetDefaultBinding(), DownloadServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDownloadService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DownloadServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(DownloadServiceClient.GetBindingForEndpoint(endpointConfiguration), DownloadServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DownloadServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DownloadServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DownloadServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DownloadServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DownloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DownloadFileInfo[]> GetAllDownloadFileInfoAsync()
        {
            return base.Channel.GetAllDownloadFileInfoAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetLastDownloadFileInfoResponse> ServiceReference.IDownloadService.GetLastDownloadFileInfoAsync(ServiceReference.GetLastDownloadFileInfoRequest request)
        {
            return base.Channel.GetLastDownloadFileInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetLastDownloadFileInfoResponse> GetLastDownloadFileInfoAsync()
        {
            ServiceReference.GetLastDownloadFileInfoRequest inValue = new ServiceReference.GetLastDownloadFileInfoRequest();
            inValue.Body = new ServiceReference.GetLastDownloadFileInfoRequestBody();
            return ((ServiceReference.IDownloadService)(this)).GetLastDownloadFileInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDownloadService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDownloadService_soap))
            {
                return new System.ServiceModel.EndpointAddress("http://fias.nalog.ru/WebServices/Public/DownloadService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DownloadServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDownloadService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DownloadServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDownloadService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDownloadService_soap,
        }
    }
}
